+ source ../common/common_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Tue May 16 15:49:14 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL dnf-automatic
+ pkgs=dnf-automatic
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs dnf-automatic --node 1 --tempfile ''
+ tmpfile2='Warning: failed loading '\''/etc/yum.repos.d/openEuler.repo'\'', skipping.
Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".'
+ '[' -z '' ']'
+ tmpfile='Warning: failed loading '\''/etc/yum.repos.d/openEuler.repo'\'', skipping.
Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".'
+ service=dnf-automatic-install.service
++ date '+%Y-%m-%d %T'
+ log_time='2023-05-16 15:49:27'
+ status='inactive (dead)'
+ systemctl start dnf-automatic-install.service
Failed to start dnf-automatic-install.service: Unit dnf-automatic-install.service not found.
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Tue May 16 15:49:27 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Tue May 16 15:49:28 2023 - INFO  - Start testing...
+ systemctl status dnf-automatic-install.service
+ grep Active
+ grep -v 'inactive (dead)'
Unit dnf-automatic-install.service could not be found.
+ CHECK_RESULT 1 0 1 'There is an error for the status of dnf-automatic-install.service'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='There is an error for the status of dnf-automatic-install.service'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ test_enabled dnf-automatic-install.service
+ service=dnf-automatic-install.service
++ systemctl is-enabled dnf-automatic-install.service
Failed to get unit file state for dnf-automatic-install.service: No such file or directory
+ state=
+ '[' '' == enabled ']'
+ '[' '' == disabled ']'
+ '[' '' == masked ']'
+ '[' '' == static ']'
+ LOG_INFO 'Unit is indirect, ignoring.'
+ message='Unit is indirect, ignoring.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Unit is indirect, ignoring.'
Tue May 16 15:49:28 2023 - INFO  - Unit is indirect, ignoring.
+ grep -i 'fail\|error'
+ journalctl --since '2023-05-16 15:49:27' -u dnf-automatic-install.service
+ grep -v '_sasl_plugin_load failed on sasl_canonuser_init'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
+ grep -v libgpg-error
+ CHECK_RESULT 1 0 1 'There is an error message for the log of dnf-automatic-install.service'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of dnf-automatic-install.service'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Tue May 16 15:49:29 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z ''
+ test 0 -eq 0
+ LOG_INFO 'succeed to execute the case.'
+ message='succeed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'succeed to execute the case.'
Tue May 16 15:49:29 2023 - INFO  - succeed to execute the case.
+ exec_result=
+ exit 0
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue May 16 15:49:30 2023 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z Warning: failed loading '/etc/yum.repos.d/openEuler.repo', skipping.
Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d". ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile 'Warning: failed loading '\''/etc/yum.repos.d/openEuler.repo'\'', skipping.
Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".'
Traceback (most recent call last):
  File "/root/mugen/libs/locallibs/rpm_manage.py", line 181, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/mugen/libs/locallibs/rpm_manage.py", line 152, in rpm_remove
    with open(tmpfile, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Warning: failed loading \'/etc/yum.repos.d/openEuler.repo\', skipping.\nError: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".'
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue May 16 15:49:32 2023 - INFO  - End to restore the test environment.
